import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import { AuthProvider } from "@/hooks/useAuth";
import ProtectedRoute from "@/components/ProtectedRoute";

import Index from "./pages/Index";
import Login from "./pages/Auth";       // or ./pages/Login (pick one)
import Register from "./pages/Register";
import Dashboard from "./pages/Dashboard";
import Tasks from "./pages/Tasks";
import Analytics from "./pages/Analytics";
import Team from "./pages/Team";
import Settings from "./pages/Settings";
import NotFound from "./pages/NotFound";
import AppLayout from "@/components/layout/AppLayout";

const queryClient = new QueryClient();

const App = () => (
  // ✅ Router must be above anything that calls useNavigate (AuthProvider)
    <BrowserRouter>
        <QueryClientProvider client={queryClient}>
              <AuthProvider>
                      <TooltipProvider>
                                <Toaster />
                                          <Sonner />
                                                    <Routes>
                                                                {/* Public */}
                                                                            <Route path="/" element={<Index />} />
                                                                                        <Route path="/login" element={<Login />} />
                                                                                                    <Route path="/register" element={<Register />} />

                                                                                                                {/* Private (wrapped in AppLayout) */}
                                                                                                                            <Route
                                                                                                                                          path="/app"
                                                                                                                                                        element={
                                                                                                                                                                        <ProtectedRoute>
                                                                                                                                                                                          <AppLayout><Dashboard /></AppLayout>
                                                                                                                                                                                                          </ProtectedRoute>
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                <Route
                                                                                                                                                                                                                                                              path="/tasks"
                                                                                                                                                                                                                                                                            element={
                                                                                                                                                                                                                                                                                            <ProtectedRoute>
                                                                                                                                                                                                                                                                                                              <AppLayout><Tasks /></AppLayout>
                                                                                                                                                                                                                                                                                                                              </ProtectedRoute>
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                    <Route
                                                                                                                                                                                                                                                                                                                                                                                  path="/analytics"
                                                                                                                                                                                                                                                                                                                                                                                                element={
                                                                                                                                                                                                                                                                                                                                                                                                                <ProtectedRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <AppLayout><Analytics /></AppLayout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </ProtectedRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      path="/team"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ProtectedRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <AppLayout><Team /></AppLayout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </ProtectedRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Route
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          path="/settings"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ProtectedRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <AppLayout><Settings /></AppLayout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ProtectedRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Catch-all */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Route path="*" element={<NotFound />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Routes>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </TooltipProvider>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </AuthProvider>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </QueryClientProvider>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </BrowserRouter>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default App;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          